apiVersion: v1
kind: Service
metadata:
  name: shopapp-service
spec:
  selector:
    app: shopapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
